version: '3.8'
services:
  nginx:
    image: kirillfedoseev/nginx_reverseproxy:v1
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_reverseproxy
    depends_on:
      - web
    networks:
      - docker-network
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 3
  web:
    image: kirillfedoseev/flask:v1
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        BASE_DIR: ./web
    container_name: flask_webapp
    environment:
      - FLASK_APP=application/main.py
    command: python application/main.py
    networks:
      docker-network:
        aliases:
          - flask_webapp
    deploy:
      mode: replicated
      replicas: 3
  db:
    image: kirillfedoseev/mongodb:v1
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        BASE_DIR: ./db
    networks:
      docker-network:
        aliases:
          - db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.db==true"
networks:
  docker-network:
